<template>
  <v-navigation-drawer v-model="open" temporary location="right" width="520" class="expert-finding-drawer">
    <template v-if="finding"><div class="expert-finding-drawer__header"><div><span>Результат исследования №{{ finding.number }}</span><h2>{{ finding.title }}</h2></div><v-btn icon="mdi-close" variant="text" @click="open = false" /></div><div class="expert-finding-drawer__content"><v-chip variant="tonal" color="primary" size="small">{{ finding.typeLabel }}</v-chip><v-chip class="expert-finding-drawer__status" variant="tonal" :color="statusColor(finding.status)" size="small">{{ finding.status }}</v-chip><section v-for="item in details" :key="item.label"><h3>{{ item.label }}</h3><p>{{ item.value }}</p></section><section><h3>Источники</h3><div class="expert-finding-drawer__sources"><v-chip v-for="source in finding.sources" :key="source.id" size="small" prepend-icon="mdi-file-outline">{{ source.label }}<template v-if="source.detail"> · {{ source.detail }}</template></v-chip></div></section><section v-if="linkedMaterials.length"><h3>Материалы / доказательства</h3><div class="expert-finding-drawer__references"><v-chip v-for="material in linkedMaterials" :key="material.id" size="small" :prepend-icon="material.icon">{{ material.name }}</v-chip></div></section><section v-if="linkedNormatives.length"><h3>Нормативы / критерии</h3><div class="expert-finding-drawer__references"><v-chip v-for="normative in linkedNormatives" :key="normative.id" size="small" prepend-icon="mdi-book-check-outline">{{ normative.code }}</v-chip></div></section><section v-if="finding.images?.length"><h3>Изображения</h3><div class="expert-finding-drawer__images"><div v-for="image in finding.images" :key="image"><v-icon icon="mdi-image-outline" />{{ image }}</div></div></section></div><div class="expert-finding-drawer__footer"><v-select :model-value="finding.status" :items="statuses" label="Статус подтверждения" variant="outlined" density="compact" hide-details @update:model-value="$emit('action', 'Изменение статуса')" /></div></template>
  </v-navigation-drawer>
</template>
<script setup lang="ts">
import { computed } from 'vue'
import type { ExpertFinding, ExpertProject } from '../../types'
const props = defineProps<{ finding: ExpertFinding | null; project: ExpertProject }>(); const open = defineModel<boolean>({ required: true }); defineEmits<{ (event: 'action', action: string): void }>()
const statuses = ['Предложено AI', 'Подтверждено экспертом', 'Отклонено экспертом']
const researchObject = computed(() => props.project.researchObjects.find((item) => item.id === props.finding?.researchObjectId))
const linkedMaterials = computed(() => props.project.materials.filter((item) => props.finding?.materialIds?.includes(item.id)))
const linkedNormatives = computed(() => props.project.normatives.filter((item) => props.finding?.normativeReferenceIds?.includes(item.id)))
const details = computed(() => { const f = props.finding; if (!f) return []; return [{ label: 'Объект исследования', value: researchObject.value?.name ?? f.object }, { label: 'Описание', value: f.description }, { label: 'Фактические данные', value: f.factualData }, { label: 'Измеренное значение', value: f.measurement }, { label: 'Причина', value: f.cause }, { label: 'Нормативное сопоставление', value: f.normativeComparison }, { label: 'Способ устранения / рекомендации', value: f.recommendation }, { label: 'Расчёты', value: f.calculation }].filter((item): item is { label: string; value: string } => Boolean(item.value)) })
function statusColor(status: ExpertFinding['status']) { if (status === 'Подтверждено экспертом') return 'success'; if (status === 'Отклонено экспертом') return 'error'; return 'warning' }
</script>
<style scoped>
.expert-finding-drawer :deep(.v-navigation-drawer__content) { display: flex; flex-direction: column; }.expert-finding-drawer__header { display: flex; justify-content: space-between; gap: 12px; padding: 20px; border-bottom: 1px solid rgba(var(--v-theme-outline-variant), .55); }.expert-finding-drawer__header span { color: rgb(var(--v-theme-primary)); font-size: .68rem; font-weight: 800; text-transform: uppercase; }.expert-finding-drawer__header h2 { margin: 5px 0 0; font-size: 1.1rem; }.expert-finding-drawer__content { flex: 1; overflow: auto; padding: 20px; }.expert-finding-drawer__content section { margin-top: 20px; }.expert-finding-drawer__content h3 { margin: 0 0 5px; color: rgba(var(--v-theme-on-surface-variant), .72); font-size: .7rem; letter-spacing: .04em; text-transform: uppercase; }.expert-finding-drawer__content p { margin: 0; font-size: .82rem; line-height: 1.5; }.expert-finding-drawer__sources { display: flex; flex-wrap: wrap; gap: 6px; }.expert-finding-drawer__images { display: grid; grid-template-columns: repeat(2, 1fr); gap: 8px; }.expert-finding-drawer__images div { display: grid; place-items: center; gap: 5px; min-height: 90px; border-radius: var(--md-sys-shape-corner-medium); background: rgb(var(--v-theme-surface-container-low)); font-size: .7rem; }.expert-finding-drawer__footer { padding: 14px 20px; border-top: 1px solid rgba(var(--v-theme-outline-variant), .55); }
.expert-finding-drawer__status { margin-left: 6px; }
.expert-finding-drawer__references { display: flex; flex-wrap: wrap; gap: 6px; }
</style>
