server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php;
    
    # Лимит размера загружаемых файлов - 72 МБ
    client_max_body_size 72M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /price-indices-public-calculator.js {
        alias /var/www/assets/price-indices-public-calculator.js;
        add_header Cache-Control "public, max-age=0, must-revalidate" always;
    }

    location = /price-indices-public-chart.js {
        alias /var/www/assets/price-indices-public-chart.js;
        add_header Cache-Control "public, max-age=0, must-revalidate" always;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout 300;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        include fastcgi_params;
    }
}
