<?php
return [
    'chat' => [
        'history_limit' => (int) env('EXPERT_CHAT_HISTORY_LIMIT', 20),
        'idempotency_lock_seconds' => (int) env('EXPERT_CHAT_IDEMPOTENCY_LOCK_SECONDS', 900),
        'idempotency_wait_seconds' => (int) env('EXPERT_CHAT_IDEMPOTENCY_WAIT_SECONDS', 5),
    ],
    'streaming' => [
        'lock_seconds' => (int) env('EXPERT_STREAM_LOCK_SECONDS', 900),
        'run_ttl_seconds' => (int) env('EXPERT_STREAM_RUN_TTL_SECONDS', 1800),
        'time_to_first_token_seconds' => (int) env('EXPERT_STREAM_TTFB_SECONDS', 45),
        'idle_timeout_seconds' => (int) env('EXPERT_STREAM_IDLE_TIMEOUT_SECONDS', 45),
        'absolute_timeout_seconds' => (int) env('EXPERT_STREAM_ABSOLUTE_TIMEOUT_SECONDS', 600),
        'heartbeat_seconds' => (int) env('EXPERT_STREAM_HEARTBEAT_SECONDS', 15),
    ],
    'material_context' => [
        'xlsx_enabled' => true,
        'max_materials_per_message' => (int) env('EXPERT_CHAT_MAX_MATERIALS_PER_MESSAGE', 5),
        'max_total_material_bytes' => (int) env('EXPERT_CHAT_MAX_TOTAL_MATERIAL_BYTES', 10 * 1024 * 1024),
        'max_material_bytes' => (int) env('EXPERT_CHAT_MAX_MATERIAL_BYTES', 5 * 1024 * 1024),
        'max_extracted_chars_per_material' => (int) env('EXPERT_CHAT_MAX_EXTRACTED_CHARS_PER_MATERIAL', 30000),
        'max_total_extracted_chars' => (int) env('EXPERT_CHAT_MAX_TOTAL_EXTRACTED_CHARS', 80000),
        'max_spreadsheet_uncompressed_bytes' => (int) env('EXPERT_CHAT_MAX_SPREADSHEET_UNCOMPRESSED_BYTES', 20 * 1024 * 1024),
        'max_spreadsheet_cells' => (int) env('EXPERT_CHAT_MAX_SPREADSHEET_CELLS', 5000),
        'max_docx_archive_entries' => (int) env('EXPERT_CHAT_MAX_DOCX_ARCHIVE_ENTRIES', 200),
        'max_docx_uncompressed_bytes' => (int) env('EXPERT_CHAT_MAX_DOCX_UNCOMPRESSED_BYTES', 20 * 1024 * 1024),
        'max_docx_xml_entry_bytes' => (int) env('EXPERT_CHAT_MAX_DOCX_XML_ENTRY_BYTES', 5 * 1024 * 1024),
        'max_xlsx_archive_entries' => (int) env('EXPERT_CHAT_MAX_XLSX_ARCHIVE_ENTRIES', 500),
        'max_xlsx_xml_entry_bytes' => (int) env('EXPERT_CHAT_MAX_XLSX_XML_ENTRY_BYTES', 5 * 1024 * 1024),
        'max_zip_compression_ratio' => (int) env('EXPERT_CHAT_MAX_ZIP_COMPRESSION_RATIO', 100),
    ],
    'vision' => [
        'max_images_per_message' => (int) env('EXPERT_VISION_MAX_IMAGES_PER_MESSAGE', 4),
        'max_source_bytes' => (int) env('EXPERT_VISION_MAX_SOURCE_BYTES', 15 * 1024 * 1024),
        'max_width' => (int) env('EXPERT_VISION_MAX_WIDTH', 10000),
        'max_height' => (int) env('EXPERT_VISION_MAX_HEIGHT', 10000),
        'max_pixels' => (int) env('EXPERT_VISION_MAX_PIXELS', 25_000_000),
        'max_output_width' => (int) env('EXPERT_VISION_MAX_OUTPUT_WIDTH', 2048),
        'max_output_height' => (int) env('EXPERT_VISION_MAX_OUTPUT_HEIGHT', 2048),
        'jpeg_quality' => (int) env('EXPERT_VISION_JPEG_QUALITY', 88),
        'max_prepared_image_bytes' => (int) env('EXPERT_VISION_MAX_PREPARED_IMAGE_BYTES', 5 * 1024 * 1024),
        'max_total_vision_bytes' => (int) env('EXPERT_VISION_MAX_TOTAL_BYTES', 12 * 1024 * 1024),
    ],
    'pdf_ocr' => [
        'enabled' => (bool) env('EXPERT_PDF_OCR_ENABLED', true),
        'engine' => (string) env('EXPERT_PDF_OCR_ENGINE', 'mistral-ocr'),
        'cache_version' => (string) env('EXPERT_PDF_OCR_CACHE_VERSION', 'v1'),
        'min_usable_text_chars' => (int) env('EXPERT_PDF_OCR_MIN_USABLE_TEXT_CHARS', 16),
        'max_pdfs' => (int) env('EXPERT_PDF_OCR_MAX_PDFS', 2),
        'max_source_bytes' => (int) env('EXPERT_PDF_OCR_MAX_SOURCE_BYTES', 20 * 1024 * 1024),
        'max_pages_per_pdf' => (int) env('EXPERT_PDF_OCR_MAX_PAGES_PER_PDF', 100),
        'max_total_pages' => (int) env('EXPERT_PDF_OCR_MAX_TOTAL_PAGES', 150),
        'max_base64_request_bytes' => (int) env('EXPERT_PDF_OCR_MAX_BASE64_REQUEST_BYTES', 56 * 1024 * 1024),
        'max_annotation_text_chars' => (int) env('EXPERT_PDF_OCR_MAX_ANNOTATION_TEXT_CHARS', 500000),
        'max_annotation_images_per_pdf' => (int) env('EXPERT_PDF_OCR_MAX_ANNOTATION_IMAGES_PER_PDF', 8),
        'max_annotation_image_bytes' => (int) env('EXPERT_PDF_OCR_MAX_ANNOTATION_IMAGE_BYTES', 5 * 1024 * 1024),
        'max_annotation_images_bytes' => (int) env('EXPERT_PDF_OCR_MAX_ANNOTATION_IMAGES_BYTES', 20 * 1024 * 1024),
        'max_cache_bytes' => (int) env('EXPERT_PDF_OCR_MAX_CACHE_BYTES', 32 * 1024 * 1024),
    ],
    'pdf_processing' => [
        'text_engine' => (string) env('EXPERT_PDF_TEXT_ENGINE', 'cloudflare-ai'),
        'ocr_engine' => (string) env('EXPERT_PDF_OCR_ENGINE', 'mistral-ocr'),
    ],
    'material_max_kib' => (int) env('EXPERT_MATERIAL_MAX_KIB', 51200),
    'material_extensions' => ['txt', 'md', 'pdf', 'docx', 'xlsx', 'jpg', 'jpeg', 'png', 'webp'],
    'material_mime_types' => [
        'text/plain', 'text/markdown',
        'application/pdf',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'image/jpeg', 'image/png', 'image/webp',
    ],
    'material_thumbnails' => [
        'cache_version' => (string) env('EXPERT_MATERIAL_THUMBNAIL_CACHE_VERSION', 'v1'),
        'max_source_bytes' => (int) env('EXPERT_MATERIAL_THUMBNAIL_MAX_SOURCE_BYTES', 15 * 1024 * 1024),
        'max_width' => (int) env('EXPERT_MATERIAL_THUMBNAIL_MAX_WIDTH', 10000),
        'max_height' => (int) env('EXPERT_MATERIAL_THUMBNAIL_MAX_HEIGHT', 10000),
        'max_pixels' => (int) env('EXPERT_MATERIAL_THUMBNAIL_MAX_PIXELS', 25_000_000),
        'max_output_width' => (int) env('EXPERT_MATERIAL_THUMBNAIL_MAX_OUTPUT_WIDTH', 320),
        'max_output_height' => (int) env('EXPERT_MATERIAL_THUMBNAIL_MAX_OUTPUT_HEIGHT', 320),
        'jpeg_quality' => (int) env('EXPERT_MATERIAL_THUMBNAIL_JPEG_QUALITY', 82),
        'cache_control' => (string) env('EXPERT_MATERIAL_THUMBNAIL_CACHE_CONTROL', 'private, max-age=3600, must-revalidate'),
    ],
    'storage_cleanup_retry_delays_seconds' => [60, 300, 1800, 7200, 86400],
];
