<template>
  <div class="expert-section-page expert-research"><div class="expert-section-page__header"><div><span>Структурированные данные</span><h1>Исследование</h1><p>Факты, измерения, обстоятельства, расчёты и выводы в едином слое проекта.</p></div><v-btn color="primary" variant="flat" prepend-icon="mdi-plus" @click="notify('Добавление записи')">Добавить запись</v-btn></div>
    <v-tabs v-model="tab" color="primary" class="expert-research__tabs"><v-tab v-for="item in tabs" :key="item.value" :value="item.value">{{ item.label }}<v-chip size="x-small" class="ml-2">{{ countFor(item.value) }}</v-chip></v-tab></v-tabs><v-divider class="mb-4" />
    <div v-if="visibleFindings.length" class="expert-research__list"><button v-for="finding in visibleFindings" :key="finding.id" type="button" class="expert-finding-card" @click="openFinding(finding)"><div class="expert-finding-card__number">{{ finding.number }}</div><div class="expert-finding-card__body"><div><v-chip size="x-small" variant="tonal" color="primary">{{ finding.typeLabel }}</v-chip><v-chip size="x-small" variant="text">{{ finding.status }}</v-chip></div><h2>{{ finding.title }}</h2><p>{{ finding.description }}</p><small><v-icon icon="mdi-crosshairs-gps" size="14" />{{ finding.object }}<template v-if="finding.measurement"> · {{ finding.measurement }}</template></small></div><v-icon icon="mdi-chevron-right" /></button></div>
    <div v-else class="expert-empty"><v-icon icon="mdi-microscope" size="44" /><h2>Структурированные данные пока отсутствуют</h2><p>Они смогут появляться автоматически в процессе работы с Prism AI или добавляться вручную.</p></div>
    <ExpertFindingDrawer v-model="drawerOpen" :finding="selectedFinding" @action="notify" /><v-snackbar v-model="snackbarOpen">{{ snackbarText }}</v-snackbar>
  </div>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'; import ExpertFindingDrawer from '../components/research/ExpertFindingDrawer.vue'; import type { ExpertFinding, ExpertFindingType, ExpertProject } from '../types'
const props = defineProps<{ project: ExpertProject }>(); const tab = ref('all'); const drawerOpen = ref(false); const selectedFinding = ref<ExpertFinding | null>(null); const snackbarOpen = ref(false); const snackbarText = ref('')
const tabs = [{ label: 'Факты', value: 'fact' }, { label: 'Измерения', value: 'measurement' }, { label: 'Выявленные обстоятельства', value: 'all' }, { label: 'Расчёты', value: 'calculation' }, { label: 'Выводы', value: 'conclusion' }]
const visibleFindings = computed(() => tab.value === 'all' ? props.project.findings : props.project.findings.filter((finding) => finding.type === tab.value)); function countFor(value: string) { return value === 'all' ? props.project.findings.length : props.project.findings.filter((finding) => finding.type === value as ExpertFindingType).length }; function openFinding(finding: ExpertFinding) { selectedFinding.value = finding; drawerOpen.value = true }; function notify(action: string) { snackbarText.value = `${action}: функция будет подключена на следующем этапе`; snackbarOpen.value = true }
</script>
<style scoped>
.expert-section-page { padding: 26px; }.expert-section-page__header { display: flex; align-items: flex-end; justify-content: space-between; gap: 20px; margin-bottom: 18px; }.expert-section-page__header > div > span { color: rgb(var(--v-theme-primary)); font-size: .68rem; font-weight: 800; letter-spacing: .09em; text-transform: uppercase; }.expert-section-page h1 { margin: 4px 0; font-size: 1.55rem; }.expert-section-page__header p { margin: 0; color: rgba(var(--v-theme-on-surface-variant), .75); font-size: .8rem; }.expert-research__tabs { max-width: 100%; overflow: hidden; }.expert-research__list { display: grid; gap: 10px; }.expert-finding-card { display: grid; grid-template-columns: auto minmax(0, 1fr) auto; align-items: center; gap: 14px; width: 100%; padding: 16px; border: 1px solid rgba(var(--v-theme-outline-variant), .62); border-radius: var(--md-sys-shape-corner-large); color: rgb(var(--v-theme-on-surface)); background: rgb(var(--v-theme-surface)); cursor: pointer; text-align: left; font: inherit; }.expert-finding-card:hover { border-color: rgba(var(--v-theme-primary), .45); }.expert-finding-card__number { display: grid; place-items: center; width: 38px; height: 38px; border-radius: 50%; color: rgb(var(--v-theme-on-primary-container)); background: rgb(var(--v-theme-primary-container)); font-weight: 800; }.expert-finding-card h2 { margin: 7px 0 4px; font-size: .9rem; }.expert-finding-card p { margin: 0 0 7px; color: rgba(var(--v-theme-on-surface-variant), .78); font-size: .77rem; }.expert-finding-card small { display: flex; align-items: center; gap: 4px; color: rgba(var(--v-theme-on-surface-variant), .68); font-size: .68rem; }.expert-empty { display: grid; justify-items: center; padding: 64px 20px; text-align: center; color: rgba(var(--v-theme-on-surface-variant), .75); }.expert-empty h2 { margin: 14px 0 4px; color: rgb(var(--v-theme-on-surface)); font-size: 1.05rem; }.expert-empty p { max-width: 480px; margin: 0; font-size: .8rem; }
@media (max-width: 760px) { .expert-section-page { padding: 18px 13px; }.expert-section-page__header { align-items: stretch; flex-direction: column; }.expert-research__tabs { max-width: calc(100vw - 60px); }.expert-finding-card { grid-template-columns: auto minmax(0, 1fr); }.expert-finding-card > .v-icon { display: none; } }
</style>
