<template>
  <div class="expert-versions"><div class="expert-versions__header"><span>История документа</span><h1>Версии</h1><p>Контрольные состояния заключения и исследовательских данных.</p></div><div class="expert-versions__timeline"><article v-for="revision in project.revisions" :key="revision.id" class="expert-version" :class="{ 'expert-version--current': revision.current }"><div class="expert-version__marker"><v-icon :icon="revision.current ? 'mdi-check' : 'mdi-history'" size="18" /></div><div><div class="expert-version__title"><strong>{{ revision.label }}</strong><v-chip v-if="revision.current" size="x-small" color="primary" variant="tonal">Текущая</v-chip></div><span>{{ revision.createdAt }}</span><p>{{ revision.current ? 'Последняя сохранённая версия документа' : 'Предыдущая версия экспертного документа' }}</p></div><v-btn variant="text" size="small" @click="notify(revision.current ? 'Просмотр текущей версии' : 'Открытие версии')">Открыть</v-btn></article></div><v-snackbar v-model="snackbarOpen">{{ snackbarText }}</v-snackbar></div>
</template>
<script setup lang="ts">
import { ref } from 'vue'; import type { ExpertProject } from '../types'; defineProps<{ project: ExpertProject }>(); const snackbarOpen = ref(false); const snackbarText = ref(''); function notify(action: string) { snackbarText.value = `${action}: versioning будет подключён на следующем этапе`; snackbarOpen.value = true }
</script>
<style scoped>
.expert-versions { max-width: 820px; padding: 28px; }.expert-versions__header > span { color: rgb(var(--v-theme-primary)); font-size: .68rem; font-weight: 800; letter-spacing: .09em; text-transform: uppercase; }.expert-versions h1 { margin: 4px 0; font-size: 1.55rem; }.expert-versions__header p { margin: 0 0 26px; color: rgba(var(--v-theme-on-surface-variant), .75); font-size: .8rem; }.expert-versions__timeline { position: relative; display: grid; gap: 10px; }.expert-versions__timeline::before { content: ''; position: absolute; top: 28px; bottom: 28px; left: 24px; width: 1px; background: rgba(var(--v-theme-outline-variant), .8); }.expert-version { position: relative; display: grid; grid-template-columns: auto minmax(0, 1fr) auto; align-items: center; gap: 14px; padding: 16px; border: 1px solid rgba(var(--v-theme-outline-variant), .62); border-radius: var(--md-sys-shape-corner-large); background: rgb(var(--v-theme-surface)); }.expert-version--current { border-color: rgba(var(--v-theme-primary), .42); }.expert-version__marker { z-index: 1; display: grid; place-items: center; width: 34px; height: 34px; border-radius: 50%; color: rgb(var(--v-theme-primary)); background: rgb(var(--v-theme-primary-container)); }.expert-version__title { display: flex; align-items: center; gap: 8px; }.expert-version span { color: rgba(var(--v-theme-on-surface-variant), .68); font-size: .68rem; }.expert-version p { margin: 5px 0 0; color: rgba(var(--v-theme-on-surface-variant), .78); font-size: .75rem; }
@media (max-width: 600px) { .expert-versions { padding: 18px 13px; }.expert-version { grid-template-columns: auto 1fr; }.expert-version > .v-btn { grid-column: 2; justify-self: start; } }
</style>
