<template>
  <div class="expert-normatives">
    <div class="expert-normatives__header"><div><span>Связанные источники</span><h1>Нормативы проекта</h1><p>Нормативные документы, используемые в исследовании и заключении.</p></div><v-btn color="primary" variant="flat" prepend-icon="mdi-plus" @click="notify('Добавление норматива')">Добавить норматив</v-btn></div>
    <section><h2>Подключённые</h2><div class="expert-normatives__grid"><article v-for="normative in connected" :key="normative.id" class="expert-normative-card"><div class="expert-normative-card__icon"><v-icon icon="mdi-book-check-outline" /></div><div><strong>{{ normative.code }}</strong><h3>{{ normative.title }}</h3><p>{{ normative.applicability }}</p></div><v-menu><template #activator="{ props: menuProps }"><v-btn v-bind="menuProps" icon="mdi-dots-vertical" variant="text" size="small" /></template><v-list density="compact"><v-list-item title="Открыть" prepend-icon="mdi-open-in-new" @click="notify('Открытие норматива')"/><v-list-item title="Отключить" prepend-icon="mdi-link-off" @click="notify('Отключение норматива')"/></v-list></v-menu></article></div></section>
    <section class="expert-normatives__recommended"><div class="expert-normatives__section-title"><div><v-icon icon="mdi-auto-fix" color="primary" /><h2>Prism AI рекомендует</h2></div><span>На основе направления и материалов проекта</span></div><div class="expert-normatives__grid"><article v-for="normative in recommended" :key="normative.id" class="expert-normative-card expert-normative-card--recommended"><div class="expert-normative-card__icon"><v-icon icon="mdi-book-plus-outline" /></div><div><strong>{{ normative.code }}</strong><h3>{{ normative.title }}</h3><p v-if="normative.recommendationReason"><b>Почему рекомендован:</b> {{ normative.recommendationReason }}</p><p><b>Область применения:</b> {{ normative.applicability }}</p><v-chip size="x-small" variant="tonal" :color="normative.status === 'Действующий' ? 'success' : 'warning'">{{ normative.status ?? 'Требует проверки' }}</v-chip></div><div class="expert-normative-card__actions"><v-btn variant="text" size="small" @click="notify('Просмотр норматива')">Просмотреть</v-btn><v-btn color="primary" variant="tonal" size="small" @click="notify('Подключение норматива')">Подключить</v-btn></div></article></div></section>
    <v-snackbar v-model="snackbarOpen">{{ snackbarText }}</v-snackbar>
  </div>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'; import type { ExpertProject } from '../types'; const props = defineProps<{ project: ExpertProject }>(); const snackbarOpen = ref(false); const snackbarText = ref(''); const connected = computed(() => props.project.normatives.filter((item) => item.connected)); const recommended = computed(() => props.project.normatives.filter((item) => item.recommended)); function notify(action: string) { snackbarText.value = `${action}: функция будет подключена на следующем этапе`; snackbarOpen.value = true }
</script>
<style scoped>
.expert-normatives { padding: 26px; }.expert-normatives__header { display: flex; align-items: flex-end; justify-content: space-between; gap: 20px; margin-bottom: 24px; }.expert-normatives__header > div > span { color: rgb(var(--v-theme-primary)); font-size: .68rem; font-weight: 800; letter-spacing: .09em; text-transform: uppercase; }.expert-normatives h1 { margin: 4px 0; font-size: 1.55rem; }.expert-normatives__header p { margin: 0; color: rgba(var(--v-theme-on-surface-variant), .75); font-size: .8rem; }.expert-normatives section > h2, .expert-normatives__section-title h2 { margin: 0 0 11px; font-size: .94rem; }.expert-normatives__grid { display: grid; gap: 10px; }.expert-normative-card { display: grid; grid-template-columns: auto minmax(0, 1fr) auto; align-items: start; gap: 14px; padding: 16px; border: 1px solid rgba(var(--v-theme-outline-variant), .62); border-radius: var(--md-sys-shape-corner-large); background: rgb(var(--v-theme-surface)); }.expert-normative-card__icon { display: grid; place-items: center; width: 40px; height: 40px; border-radius: var(--md-sys-shape-corner-medium); color: rgb(var(--v-theme-primary)); background: rgba(var(--v-theme-primary), .09); }.expert-normative-card strong { color: rgb(var(--v-theme-primary)); font-size: .8rem; }.expert-normative-card h3 { margin: 3px 0 6px; font-size: .86rem; }.expert-normative-card p { margin: 0; color: rgba(var(--v-theme-on-surface-variant), .76); font-size: .73rem; line-height: 1.45; }.expert-normatives__recommended { margin-top: 28px; padding: 18px; border-radius: var(--md-sys-shape-corner-extra-large); background: rgba(var(--v-theme-primary), .045); }.expert-normatives__section-title { display: flex; align-items: flex-end; justify-content: space-between; gap: 12px; margin-bottom: 12px; }.expert-normatives__section-title > div { display: flex; align-items: center; gap: 8px; }.expert-normatives__section-title h2 { margin: 0; }.expert-normatives__section-title > span { color: rgba(var(--v-theme-on-surface-variant), .68); font-size: .7rem; }.expert-normative-card--recommended { border-style: dashed; }
@media (max-width: 700px) { .expert-normatives { padding: 18px 13px; }.expert-normatives__header { align-items: stretch; flex-direction: column; }.expert-normatives__recommended { padding: 12px; }.expert-normatives__section-title { align-items: flex-start; flex-direction: column; }.expert-normative-card { grid-template-columns: auto minmax(0, 1fr); }.expert-normative-card > .v-btn, .expert-normative-card > .v-menu { grid-column: 2; justify-self: start; } }
.expert-normative-card--recommended p + p { margin-top: 7px; }
.expert-normative-card__actions { display: flex; flex-wrap: wrap; justify-content: flex-end; gap: 4px; }
@media (max-width: 700px) { .expert-normative-card__actions { grid-column: 2; justify-self: start; } }
</style>
