import type { ThemeDefinition } from 'vuetify'

const md3LightColors = {
  background: '#f8f5ff',
  surface: '#fcf8ff',
  'surface-bright': '#fcf8ff',
  'surface-dim': '#ddd9e0',
  'surface-variant': '#e7e0eb',
  'surface-container-lowest': '#ffffff',
  'surface-container-low': '#f6f1f8',
  'surface-container': '#f0ebf2',
  'surface-container-high': '#ebe5ed',
  'surface-container-highest': '#e5e0e7',
  'on-background': '#1d1b20',
  'on-surface': '#1d1b20',
  'on-surface-variant': '#49454f',
  primary: '#6750a4',
  'primary-darken-1': '#4f378b',
  'on-primary': '#ffffff',
  'primary-container': '#e9ddff',
  'on-primary-container': '#22005d',
  secondary: '#625b71',
  'on-secondary': '#ffffff',
  'secondary-container': '#e8def8',
  'on-secondary-container': '#1e192b',
  tertiary: '#7d5260',
  'on-tertiary': '#ffffff',
  'tertiary-container': '#ffd8e4',
  'on-tertiary-container': '#31111d',
  error: '#ba1a1a',
  'on-error': '#ffffff',
  'error-container': '#ffdad6',
  'on-error-container': '#410002',
  success: '#2e7d32',
  warning: '#b26a00',
  info: '#28638a',
  outline: '#7a757f',
  'outline-variant': '#cbc4cf',
  'inverse-surface': '#322f35',
  'inverse-on-surface': '#f5eff7',
  'inverse-primary': '#cfbcff',
}

const md3DarkColors = {
  background: '#141218',
  surface: '#141218',
  'surface-bright': '#3b383e',
  'surface-dim': '#141218',
  'surface-variant': '#49454f',
  'surface-container-lowest': '#0f0d13',
  'surface-container-low': '#1d1b20',
  'surface-container': '#211f26',
  'surface-container-high': '#2b2930',
  'surface-container-highest': '#36343b',
  'on-background': '#e6e0e9',
  'on-surface': '#e6e0e9',
  'on-surface-variant': '#cbc4cf',
  primary: '#cfbcff',
  'primary-darken-1': '#b69df8',
  'on-primary': '#381e72',
  'primary-container': '#4f378b',
  'on-primary-container': '#e9ddff',
  secondary: '#cbc2db',
  'on-secondary': '#332d41',
  'secondary-container': '#4a4458',
  'on-secondary-container': '#e8def8',
  tertiary: '#efb8c8',
  'on-tertiary': '#4a2532',
  'tertiary-container': '#633b48',
  'on-tertiary-container': '#ffd8e4',
  error: '#ffb4ab',
  'on-error': '#690005',
  'error-container': '#93000a',
  'on-error-container': '#ffdad6',
  success: '#86d889',
  warning: '#ffb95c',
  info: '#8ecbf8',
  outline: '#948f99',
  'outline-variant': '#49454f',
  'inverse-surface': '#e6e0e9',
  'inverse-on-surface': '#322f35',
  'inverse-primary': '#6750a4',
}

const saasDarkTheme: ThemeDefinition = {
  dark: true,
  colors: {
    ...md3DarkColors,
  },
  variables: {
    'border-color': '#ffffff',
    'border-opacity': 0.08,
    'high-emphasis-opacity': 0.95,
    'medium-emphasis-opacity': 0.72,
    'disabled-opacity': 0.45,
    'hover-opacity': 0.08,
    'focus-opacity': 0.12,
    'selected-opacity': 0.1,
    'activated-opacity': 0.1,
    'pressed-opacity': 0.12,
    'dragged-opacity': 0.08,
    'theme-kbd': '#223044',
    'theme-on-kbd': '#e5e7eb',
    'theme-code': '#1b2535',
    'theme-on-code': '#e5e7eb',
  },
}

const saasLightTheme: ThemeDefinition = {
  dark: false,
  colors: {
    ...md3LightColors,
  },
}

export const saasDesignSystem = {
  themes: {
    saasDark: saasDarkTheme,
    saasLight: saasLightTheme,
    // Aliases for legacy toggles used in older layouts.
    myTheme: saasLightTheme,
    myThemeDark: saasDarkTheme,
    expertLight: saasLightTheme,
    expertDark: saasDarkTheme,
  },
  defaults: {
    global: {
      ripple: true,
    },
    VBtn: {
      rounded: 'xl',
      elevation: 0,
      density: 'compact',
      style: 'text-transform:none;letter-spacing:0;font-weight:600;',
    },
    VCard: {
      rounded: 'xl',
      elevation: 0,
    },
    VTextField: {
      density: 'compact',
      rounded: 'lg',
      variant: 'outlined',
      hideDetails: 'auto',
    },
    VSelect: {
      density: 'compact',
      rounded: 'lg',
      variant: 'outlined',
      hideDetails: 'auto',
    },
    VTextarea: {
      density: 'compact',
      rounded: 'lg',
      variant: 'outlined',
      hideDetails: 'auto',
    },
    VSwitch: {
      density: 'compact',
      inset: false,
      color: 'primary',
    },
    VDialog: {
      maxWidth: 720,
    },
    VSheet: {
      rounded: 'lg',
    },
    VListItem: {
      rounded: 'lg',
    },
    VNavigationDrawer: {
      elevation: 0,
    },
    VChip: {
      rounded: 'xl',
    },
    VDataTable: {
      density: 'comfortable',
    },
  },
}
