import type { ThemeDefinition } from 'vuetify'

const md3LightColors = {
  background: '#f8f5ff',
  surface: '#fcf8ff',
  'surface-bright': '#fcf8ff',
  'surface-dim': '#ddd9e0',
  'surface-variant': '#e7e0eb',
  'surface-container-lowest': '#ffffff',
  'surface-container-low': '#f6f1f8',
  'surface-container': '#f0ebf2',
  'surface-container-high': '#ebe5ed',
  'surface-container-highest': '#e5e0e7',
  'on-background': '#1d1b20',
  'on-surface': '#1d1b20',
  'on-surface-variant': '#49454f',
  primary: '#6750a4',
  'primary-darken-1': '#4f378b',
  'on-primary': '#ffffff',
  'primary-container': '#e9ddff',
  'on-primary-container': '#22005d',
  secondary: '#625b71',
  'on-secondary': '#ffffff',
  'secondary-container': '#e8def8',
  'on-secondary-container': '#1e192b',
  tertiary: '#7d5260',
  'on-tertiary': '#ffffff',
  'tertiary-container': '#ffd8e4',
  'on-tertiary-container': '#31111d',
  error: '#ba1a1a',
  'on-error': '#ffffff',
  'error-container': '#ffdad6',
  'on-error-container': '#410002',
  success: '#2e7d32',
  warning: '#b26a00',
  info: '#28638a',
  outline: '#7a757f',
  'outline-variant': '#cbc4cf',
  'inverse-surface': '#322f35',
  'inverse-on-surface': '#f5eff7',
  'inverse-primary': '#cfbcff',
}

const md3LightWarmColors = {
  background: '#f6f2ea',
  surface: '#fbf7f0',
  'surface-bright': '#fffaf4',
  'surface-dim': '#ddd7ce',
  'surface-variant': '#e7dfd4',
  'surface-container-lowest': '#fffdf9',
  'surface-container-low': '#f5efe6',
  'surface-container': '#efe8de',
  'surface-container-high': '#e8e1d7',
  'surface-container-highest': '#e1d9cf',
  'on-background': '#201c17',
  'on-surface': '#201c17',
  'on-surface-variant': '#5a534b',
  primary: '#6b725d',
  'primary-darken-1': '#515744',
  'on-primary': '#ffffff',
  'primary-container': '#dfe7c9',
  'on-primary-container': '#1d210f',
  secondary: '#756f62',
  'on-secondary': '#ffffff',
  'secondary-container': '#e8e1d3',
  'on-secondary-container': '#211b11',
  tertiary: '#8a655b',
  'on-tertiary': '#ffffff',
  'tertiary-container': '#ffdacc',
  'on-tertiary-container': '#34130d',
  error: '#ba1a1a',
  'on-error': '#ffffff',
  'error-container': '#ffdad6',
  'on-error-container': '#410002',
  success: '#47683f',
  warning: '#8a5d14',
  info: '#46627a',
  outline: '#8c8378',
  'outline-variant': '#d0c5b9',
  'inverse-surface': '#35302a',
  'inverse-on-surface': '#faefe7',
  'inverse-primary': '#c3cbaf',
}

const md3DarkColors = {
  background: '#141218',
  surface: '#141218',
  'surface-bright': '#3b383e',
  'surface-dim': '#141218',
  'surface-variant': '#49454f',
  'surface-container-lowest': '#0f0d13',
  'surface-container-low': '#1d1b20',
  'surface-container': '#211f26',
  'surface-container-high': '#2b2930',
  'surface-container-highest': '#36343b',
  'on-background': '#e6e0e9',
  'on-surface': '#e6e0e9',
  'on-surface-variant': '#cbc4cf',
  primary: '#cfbcff',
  'primary-darken-1': '#b69df8',
  'on-primary': '#381e72',
  'primary-container': '#4f378b',
  'on-primary-container': '#e9ddff',
  secondary: '#cbc2db',
  'on-secondary': '#332d41',
  'secondary-container': '#4a4458',
  'on-secondary-container': '#e8def8',
  tertiary: '#efb8c8',
  'on-tertiary': '#4a2532',
  'tertiary-container': '#633b48',
  'on-tertiary-container': '#ffd8e4',
  error: '#ffb4ab',
  'on-error': '#690005',
  'error-container': '#93000a',
  'on-error-container': '#ffdad6',
  success: '#86d889',
  warning: '#ffb95c',
  info: '#8ecbf8',
  outline: '#948f99',
  'outline-variant': '#49454f',
  'inverse-surface': '#e6e0e9',
  'inverse-on-surface': '#322f35',
  'inverse-primary': '#6750a4',
}

const md3DarkWarmColors = {
  background: '#171410',
  surface: '#171410',
  'surface-bright': '#403a34',
  'surface-dim': '#171410',
  'surface-variant': '#4d463f',
  'surface-container-lowest': '#120f0c',
  'surface-container-low': '#1f1b17',
  'surface-container': '#24201c',
  'surface-container-high': '#2f2a25',
  'surface-container-highest': '#3a342e',
  'on-background': '#ece4dc',
  'on-surface': '#ece4dc',
  'on-surface-variant': '#d1c5b9',
  primary: '#c3cbaf',
  'primary-darken-1': '#aab296',
  'on-primary': '#2c331f',
  'primary-container': '#434a34',
  'on-primary-container': '#dfe7c9',
  secondary: '#d0c6b7',
  'on-secondary': '#383126',
  'secondary-container': '#4d463a',
  'on-secondary-container': '#ece2d2',
  tertiary: '#f1b8a8',
  'on-tertiary': '#522117',
  'tertiary-container': '#6c3b31',
  'on-tertiary-container': '#ffdacc',
  error: '#ffb4ab',
  'on-error': '#690005',
  'error-container': '#93000a',
  'on-error-container': '#ffdad6',
  success: '#a8d49a',
  warning: '#f0bf74',
  info: '#adcbe4',
  outline: '#9c9186',
  'outline-variant': '#4d463f',
  'inverse-surface': '#ece4dc',
  'inverse-on-surface': '#35302a',
  'inverse-primary': '#6b725d',
}

const saasDarkTheme: ThemeDefinition = {
  dark: true,
  colors: {
    ...md3DarkColors,
  },
  variables: {
    'border-color': '#ffffff',
    'border-opacity': 0.08,
    'high-emphasis-opacity': 0.95,
    'medium-emphasis-opacity': 0.72,
    'disabled-opacity': 0.45,
    'hover-opacity': 0.08,
    'focus-opacity': 0.12,
    'selected-opacity': 0.1,
    'activated-opacity': 0.1,
    'pressed-opacity': 0.12,
    'dragged-opacity': 0.08,
    'theme-kbd': '#223044',
    'theme-on-kbd': '#e5e7eb',
    'theme-code': '#1b2535',
    'theme-on-code': '#e5e7eb',
  },
}

const saasDarkWarmTheme: ThemeDefinition = {
  dark: true,
  colors: {
    ...md3DarkWarmColors,
  },
  variables: {
    'border-color': '#ffffff',
    'border-opacity': 0.08,
    'high-emphasis-opacity': 0.95,
    'medium-emphasis-opacity': 0.72,
    'disabled-opacity': 0.45,
    'hover-opacity': 0.08,
    'focus-opacity': 0.12,
    'selected-opacity': 0.1,
    'activated-opacity': 0.1,
    'pressed-opacity': 0.12,
    'dragged-opacity': 0.08,
    'theme-kbd': '#2d261f',
    'theme-on-kbd': '#ece4dc',
    'theme-code': '#241f1a',
    'theme-on-code': '#ece4dc',
  },
}

const saasLightTheme: ThemeDefinition = {
  dark: false,
  colors: {
    ...md3LightColors,
  },
}

const saasLightWarmTheme: ThemeDefinition = {
  dark: false,
  colors: {
    ...md3LightWarmColors,
  },
}

export const saasDesignSystem = {
  themes: {
    saasDark: saasDarkTheme,
    saasLight: saasLightTheme,
    saasDarkWarm: saasDarkWarmTheme,
    saasLightWarm: saasLightWarmTheme,
    // Aliases for legacy toggles used in older layouts.
    myTheme: saasLightTheme,
    myThemeDark: saasDarkTheme,
    expertLight: saasLightTheme,
    expertDark: saasDarkTheme,
  },
  defaults: {
    global: {
      ripple: true,
    },
    VBtn: {
      rounded: 'xl',
      elevation: 0,
      density: 'compact',
      style: 'text-transform:none;letter-spacing:0;font-weight:600;',
    },
    VCard: {
      rounded: 'xl',
      elevation: 0,
    },
    VTextField: {
      density: 'compact',
      rounded: 'lg',
      variant: 'outlined',
      hideDetails: 'auto',
    },
    VSelect: {
      density: 'compact',
      rounded: 'lg',
      variant: 'outlined',
      hideDetails: 'auto',
    },
    VTextarea: {
      density: 'compact',
      rounded: 'lg',
      variant: 'outlined',
      hideDetails: 'auto',
    },
    VSwitch: {
      density: 'compact',
      inset: false,
      color: 'primary',
    },
    VDialog: {
      maxWidth: 720,
    },
    VSheet: {
      rounded: 'lg',
    },
    VListItem: {
      rounded: 'lg',
    },
    VNavigationDrawer: {
      elevation: 0,
    },
    VChip: {
      rounded: 'xl',
    },
    VDataTable: {
      density: 'comfortable',
    },
  },
}
